/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exerciciospoo.exercicio5.view;

import exerciciospoo.exercicio5.dao.Ficheiro3;
import exerciciospoo.exercicio5.model.Freelancer;
import exerciciospoo.exercicio5.model.Funcionario;
import exerciciospoo.exercicio5.model.Pagavel;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author liliano
 */
public final class Visual extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Visual.class.getName());
    ArrayList<Pagavel> lista = new ArrayList<>();
    String nome;
    /** private void carregarVeiculos() {
    try {
        lista = Ficheiro2.ler("funcionario.dat"); 
    } catch(Exception e) {
        lista = new ArrayList<>();
    }
}
     * Creates new form Visual
     */
    public Visual() {
        initComponents();
        carregarVeiculos();
        actualizarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoSalarioFixo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoHoras = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoSalarioHora = new javax.swing.JTextField();
        salvar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        campoTipo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel1.setText("Nome");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel2.setText("Salario Fixo");

        campoSalarioFixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSalarioFixoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel3.setText("Horas de trabalho");

        campoHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoHorasActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel4.setText("salrio/hora");

        salvar.setText("Salvar");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });

        jButton2.setText("Listar Pagamentos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel5.setText("Tipo");

        campoTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Funcionario", "freelancer" }));

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "nome", "salario fixo", "salario por hora", "horas de trabalho", "tipo"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(campoSalarioFixo, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(salvar)
                        .addGap(101, 101, 101)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(campoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(campoSalarioHora)
                        .addComponent(campoHoras, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoSalarioFixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoSalarioHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(23, 23, 23)
                .addComponent(campoHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvar)
                    .addComponent(jButton2))
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoSalarioFixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSalarioFixoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSalarioFixoActionPerformed

    private void campoHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoHorasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoHorasActionPerformed

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        nome  = campoNome.getText();
        
        double salario = 0;
        try {
           salario = Double.parseDouble(campoSalarioFixo.getText());
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Digite apenas números no campo Ano!", 
                                  "Erro de entrada", JOptionPane.ERROR_MESSAGE);
        }
        
        
        double salarioHora = 0;
        try {
           salarioHora = Double.parseDouble(campoSalarioHora.getText());
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Digite apenas números no campo Ano!", 
                                  "Erro de entrada", JOptionPane.ERROR_MESSAGE);
        }
        
        double horas = 0;
        try {
           horas = Double.parseDouble(campoHoras.getText());
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Digite apenas números no campo Ano!", 
                                  "Erro de entrada", JOptionPane.ERROR_MESSAGE);
        }
        
        String tipo = (String) campoTipo.getSelectedItem();
        
        if(tipo.equalsIgnoreCase("funcionario")){
            Funcionario f = new Funcionario(salario, nome);
            lista.add(f);
        } else {
            Freelancer v = new Freelancer(horas, salarioHora, nome);
            lista.add(v);
        }
        
        try{
           Ficheiro3.gravar(lista ,"pagavelio.dat");
       } catch(Exception e){
           JOptionPane.showMessageDialog(this, "Erro ao salvar: " + e.getMessage());
       }
        
        actualizarTabela();
    }//GEN-LAST:event_salvarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        double total = 0;
        for(Pagavel p : lista){
            total += p.calcularSalario();
        }
        JOptionPane.showMessageDialog(this, "Total a pagar: " + total);

    }//GEN-LAST:event_jButton2ActionPerformed

    public void actualizarTabela(){
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        modelo.setRowCount(0);
        
        for(Pagavel p : lista) {
            if(p instanceof Funcionario funcionario) {
                modelo.addRow(new Object[]{
                    ((Funcionario) p).getNome(),
                    funcionario.getSalarioFixo(),
                    "",
                    "",
                    "Funcionario"
                });
            } else if(p instanceof Freelancer freelancer) {
                modelo.addRow(new Object[]{
                    ((Freelancer) p).getNome(),
                    "",
                    freelancer.getSalarioHora(),
                    freelancer.getHorasTrabalhadas(),
                    "Freelancer"       
                });
    }
}
    }
    
    
     private void carregarVeiculos() {
    try {
        lista = Ficheiro3.carregar("pagavelio.dat"); 
    } catch(Exception e) {
        lista = new ArrayList<>();
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Visual().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoHoras;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoSalarioFixo;
    private javax.swing.JTextField campoSalarioHora;
    private javax.swing.JComboBox<String> campoTipo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton salvar;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
